name: maruthimedical
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.2
  http: ^1.2.1
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.3.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/carosel/ayurveda.png
    - assets/carosel/awareness.png
    - assets/carosel/savings.png
    - assets/carosel/freedelivery.png 
    - assets/categories/tableticon.png 
    - assets/categories/ayurvedicicon.png
    - assets/categories/skincareicon.png
    - assets/categories/respiratoryicon.png
    - assets/categories/syrupicon.png 
    - assets/categories/eyecareicon.png
    - assets/categories/personalcareicon.png
    - assets/categories/firstaidicon.png 
    - assets/categories/deviceicon.png 
    - assets/categories/babycareicon.png 